(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [matches] *)
module Matches
open Primitives

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** The state type used in the state-error monad *)
assume type state : Type0

(** [matches::E1] *)
type e1_t = | E1V1 : e1_t | E1V2 : e1_t | E1V3 : e1_t

(** [matches::test1] *)
let test1_fwd (x : e1_t) : result bool =
  begin match x with
  | E1V1 -> Return true
  | E1V2 -> Return true
  | E1V3 -> Return false
  end

